name: Build Dicts
on: 
  workflow_dispatch: 
  schedule: 
    - cron: "0 0 */2 * *"
  push: 
    branches: 
      - master
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout codebase
      uses: actions/checkout@v4
      
    - name: Checkout lewangdev/scel2txt
      uses: actions/checkout@v4
      with:
        repository: lewangdev/scel2txt
        path: scel2txt
        
    - name: SetPython
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
  
    - name: Build Sougou Hot Dicts
      run: |
        curl "https://pinyin.sogou.com/d/dict/download_cell.php?id=4&name=hot&f=detail" -H "Referer: http://pinyin.sogou.com/" -o ./scel2txt/scel/hot.scel
        cd ./scel2txt || exit 1
        python ./scel2txt.py
        cat luna_pinyin.sogou.dict.yaml ../sogou_hot.dict.yaml | sort | uniq > combine.yaml
        mv combine.yaml ../sogou_hot.dict.yaml

    - name: Get Rime-ice dicts
      run: |
        curl https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/8105.dict.yaml -o 8105.dict.yaml
        curl https://raw.githubusercontent.com/iDvel/rime-ice/main/cn_dicts/base.dict.yaml -o base.dict.yaml

    - name: Git push
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add ./sogou_hot.dict.yaml
        git add ./8105.dict.yaml
        git add ./base.dict.yaml
        git commit -am "update"
        git push -f
        
